#!/usr/bin/env python
#
# Stupid script to email specified text files as simple ascii attachments, no encoding.
#

import sys,os,random,string,subprocess,getopt

cfg = {"from": "", "to": False, "cc": "", "subject": False}

def usage(name):
	print "usage: %s [-f from] [-t to] [-c cc1,cc2] [-s subject] <file1> ... <filen>" % (name)
	print "To: and Subject: will be prompted for if not specified on the command line. To: is required."


if __name__ == "__main__":
	
	randchars = string.ascii_uppercase + string.ascii_lowercase + string.digits
	sepstr = "".join(random.choice(randchars) for x in range(30))
	
	try:
		opts, args = getopt.getopt(sys.argv[1:], "hf:t:c:s:")
	except getopt.GetoptError as e:
		print str(e)
		usage(sys.argv[0])
		sys.exit(1)
	
	for opt, arg in opts:
		if opt == "-h":
			usage(sys.argv[0])
			sys.exit(0)
		if opt == "-f":
			cfg['from'] = arg
		if opt == "-t":
			cfg['to'] = arg
		if opt == "-c":
			cfg['cc'] = arg
		if opt == "-s":
			cfg['subject'] = arg

	if cfg['to'] == False:
		cfg['to'] = raw_input("To: ")
	if cfg['subject'] == False:
		cfg['subject'] = raw_input("Subject: ")

	if cfg['to'] in ["", False]:
		usage(sys.argv[0])
		sys.exit(1)
	
	content = ""
	print "Enter message, end with . by itself:"
	while 1:
		newl = raw_input()
		if newl == ".":
			break
		content += newl
		content += "\n"
		
	
	msg = ""
	if cfg['from'] != "":
		msg += "From: %s\n" % (cfg['from'])
	msg += "To: %s\n" % (cfg['to'])
	if cfg['cc'] != "":
		msg += "Cc: %s\n" % (cfg['cc'])
	msg += "Subject: %s\nMIME-Version: 1.0\nContent-Type: multipart/mixed; boundary=\"%s\"\n" % (cfg['subject'], sepstr)
	msg += "Content-disposition: inline\nUser-Agent: ericmailhack 0.01\n\n"

	# main body of message, inline, not attachment
	msg += "--%s\nContent-Type: text/plain; charset=us-ascii\nContent-Disposition: inline\n\n" % (sepstr)
	msg += "%s\n" % (content)

	# create new part for each file	
	for i in args:
		try:
			f = open(i, "r")
			msg += "--%s\nContent-Type: text/plain; charset=us-ascii\n" % (sepstr)
			msg += "Content-Disposition: attachment; filename=%s\n\n" % (i)
			msg += "".join(f.readlines())
			f.close()
			msg += "\n"
		except BaseException as e:
			print "error reading file %s: %s" % (i, e)
			sys.exit(1)

	# end of the message.. 	
	msg += "--%s--\n" % (sepstr)

	# debugging	
	#print msg
	#sys.exit(0)
	proc = subprocess.Popen("sendmail -t", shell=True, stdin=subprocess.PIPE)
	out, err = proc.communicate(input=msg)
	sys.exit(0)
